import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';
import '../../../shared/services/supabase_service.dart';
import '../../../shared/models/payroll_record_model.dart';
import '../utils/payslip_generator.dart';
import '../widgets/payroll_status_badge.dart';

class EmployeeSalaryScreen extends ConsumerStatefulWidget {
  const EmployeeSalaryScreen({super.key});

  @override
  ConsumerState<EmployeeSalaryScreen> createState() => _EmployeeSalaryScreenState();
}

class _EmployeeSalaryScreenState extends ConsumerState<EmployeeSalaryScreen> {
  List<PayrollRecordModel> _records = [];
  bool _isLoading = true;

  String? _myName;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _isLoading = true);
    try {
      _records = await SupabaseService.getMyPayrollRecords();
      final profile = await SupabaseService.getCurrentProfile();
      _myName = profile?.name;
    } catch (_) {}
    if (mounted) setState(() => _isLoading = false);
  }

  Future<void> _downloadPayslip(PayrollRecordModel r) async {
    try {
      final name = _myName ?? 'Employee';
      final pdfBytes = await PayslipGenerator.generate(record: r, employeeName: name);
      final month = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][r.month - 1];
      await Printing.sharePdf(bytes: pdfBytes, filename: 'payslip_${month}_${r.year}.pdf');
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final nf = NumberFormat('#,##0.00', 'en_IN');

    return Scaffold(
      appBar: AppBar(title: const Text('My Salary')),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _records.isEmpty
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.account_balance_outlined, size: 64, color: Colors.grey.shade600),
                      const SizedBox(height: 16),
                      Text('No salary records', style: TextStyle(fontSize: 18, color: Colors.grey.shade400)),
                      const SizedBox(height: 8),
                      Text('Payroll will appear once generated by admin', style: TextStyle(fontSize: 13, color: Colors.grey.shade600)),
                    ],
                  ),
                )
              : ListView.builder(
                  padding: const EdgeInsets.all(16),
                  itemCount: _records.length,
                  itemBuilder: (context, i) {
                    final r = _records[i];
                    final month = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][r.month - 1];
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 14),
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(20),
                        child: BackdropFilter(
                          filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                          child: Container(
                            padding: const EdgeInsets.all(20),
                            decoration: BoxDecoration(
                              color: Colors.white.withValues(alpha: 0.06),
                              borderRadius: BorderRadius.circular(20),
                              border: Border.all(color: Colors.white.withValues(alpha: 0.08)),
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  children: [
                                    Text('$month ${r.year}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.white)),
                                    const Spacer(),
                                    if (r.isApproved || r.isPaid)
                                      IconButton(
                                        icon: const Icon(Icons.download, color: Color(0xFF3B82F6), size: 20),
                                        onPressed: () => _downloadPayslip(r),
                                        tooltip: 'Download Payslip',
                                      ),
                                    PayrollStatusBadge(status: r.status),
                                  ],
                                ),
                                const SizedBox(height: 20),
                                _row('Basic Salary', '₹${nf.format(r.basicSalary)}'),
                                const Divider(color: Colors.white12),
                                _row('Leave Allowed', '${r.allowedLeave} days'),
                                _row('Leave Deduction', '- ₹${nf.format(r.deductionAmount)}', color: Colors.red.shade300),
                                _row('Advance Deduction', '- ₹${nf.format(r.advanceAmount)}', color: Colors.red.shade300),
                                const Divider(color: Colors.white12),
                                _row('Final Salary', '₹${nf.format(r.finalSalary)}', bold: true, color: const Color(0xFF3B82F6)),
                              ],
                            ),
                          ),
                        ),
                      ),
                    );
                  },
                ),
    );
  }

  Widget _row(String label, String value, {bool bold = false, Color? color}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: TextStyle(color: Colors.grey.shade400, fontSize: 14)),
          Text(value, style: TextStyle(fontWeight: bold ? FontWeight.bold : FontWeight.w500, color: color ?? Colors.white, fontSize: 14)),
        ],
      ),
    );
  }
}
